### ISSUE TITLE
ORTE does not know how to route a message to the specified daemon

### ISSUE THREAD

**Issue by MenglingD** [horovod/horovod#1850]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) mxnet
2. Framework version: 1.6.0
3. Horovod version: 0.19.0
4. MPI version: 4.0.1
5. CUDA version: 10.0.130
6. NCCL version: 2.4.8
7. Python version: 3.6.9
8. OS and version: ubuntu18.04
9. GCC version: 7.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
[https://github.com/horovod/horovod/issues/504](https://github.com/horovod/horovod/issues/504)
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

I got the same situation with mpirun prompt: ORTE does not know how to route a message to the specified daemon，like issue: [https://github.com/horovod/horovod/issues/504](https://github.com/horovod/horovod/issues/504)

The training enviroment is based on docker in k8s，and all nodes can connected each other with ssh which allows passwordless authentication. And I have already check the connection between all nodes manually in master-node, even the connection between worker-nodes.

By the way, I run horovod with open mpi，and the [Hangs due to non-routed network interfaces](https://horovod.readthedocs.io/en/latest/mpirun.html) is handle by specify the network interfaces，the startup command is :
```bash
mpirun --allow-run-as-root --np 160 \
    --hostfile /tmp/hostfile \
    -bind-to none -map-by slot \
    -x NCCL_IB_DISABLE=1 \
    -x NCCL_DEBUG=INFO \
    -x PYTHONPATH=/opt/incubator-mxnet/python \
    -x MXNET_CUDNN_AUTOTUNE_DEFAULT=0 \
    -x NCCL_SOCKET_IFNAME=eth0 -mca pml ob1 \
    -mca btl ^openib -mca btl_tcp_if_include eth0 python3 tools/train_softmax.py --network resnet18_v2 --dummy-data --horovod  --epochs 5 --save-prefix models/resnet50_v2_dummy --sw-dir logs_sw --num-classes 1000 --batch-size 40960 --dtype float32 2>&1 | tee /mnt/save/logs/vc-hvd-resnet18-v2-lbs256-float32-np160.log
```
In addition, the eth0 is the only network interface that can find in container except `lo`, and I have tried replace the `eth0` with `docker0`, but I got the same error output:
```bash
Warning: Permanently added 'vc-hvd-resnet18-v2-lbs256-float32-np160-mpiworker-7.vc-hvd-resnet18-v2-lbs256-float32-np160,192.168.216.45' (ECDSA) to the list of known hosts.
Warning: Permanently added 'vc-hvd-resnet18-v2-lbs256-float32-np160-mpiworker-10.vc-hvd-resnet18-v2-lbs256-float32-np160,192.168.58.40' (ECDSA) to the list of known hosts.
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[55929,0],0] on node vc-hvd-resnet18-v2-lbs256-float32-np160-mpimaster-0
  Remote daemon: [[55929,0],11] on node vc-hvd-resnet18-v2-lbs256-float32-np160-mpiworker-10

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   vc-hvd-resnet18-v2-lbs256-float32-np160-mpimaster-0
  target node:  vc-hvd-resnet18-v2-lbs256-float32-np160-mpiworker-0

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------
[vc-hvd-resnet18-v2-lbs256-float32-np160-mpimaster-0:02871] 18 more processes have sent help message help-errmgr-base.txt / no-path
[vc-hvd-resnet18-v2-lbs256-float32-np160-mpimaster-0:02871] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```
What surprised me is that the training program can corrected start and execute when the number of node is less，but the process of training is always stuck when the number of node more.

The error information seems to imply that the part of nodes can not connected, but I have checked all connection between all nodes like said above. 

So is there anyone can do me a  favour，or some advice to dive the reason of this situation?

**Comment by MenglingD** [comment]
It's seems to the bug of openmpi，and I find analogous issues in openmpi repository. [OMPI 4.0.1 TCP connection errors beyond 86 nodes](https://github.com/open-mpi/ompi/issues/6786). And that bug fixed at 4.0.3 of openmpi，which is tested in my situation.

**Comment by Richie-yan** [comment]
Hi, @MenglingD 
I also encountered this problem and tried to upgrade openmpi to 4.0.3
But the problem still appears

**Comment by MenglingD** [comment]
> Hi, @MenglingD
> I also encountered this problem and tried to upgrade openmpi to 4.0.3
> But the problem still appears

Can you describe your situation in more details? In my situation, horovod was failed as the number of nodes is over the limit. 4.0.3 openmpi may be have some limit, which you can check.

**Comment by Richie-yan** [comment]
@MenglingD 
My situation is at 20 nodes, the job can run normally, but 40 nodes will report this error, I tried to upgrade the openmpi version did not solve the problem.
But I solved my problem by adding `-mca routed direct` to the mpirun command, 40 Nodes can run normally
