### ISSUE TITLE
Horovod fails to install via Poetry

### ISSUE THREAD

**Issue by joeyearsley** [horovod/horovod#3697]
**Environment:**
1. Framework: Tensorflow
2. Framework version: 1.8.1
3. Horovod version: 0.24.2
4. MPI version: -
5. CUDA version: -
6. NCCL version: -
7. Python version: 3.8
8. Spark / PySpark version: -
9. Ray version: -
10. OS and version: Ubuntu 22.04
11. GCC version: -
12. CMake version: - 

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Trying to install horovod via poetry and keep receiving:
```
        ModuleNotFoundError: No module named 'tensorflow'
```

If I install via pip into the virtual env directly this works, however it adds extra load onto the team as they have to remember to do this on top of poetry install. 

Cmake Output:
```
cmake /tmp/pip-req-build-69ukzo_1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/tmp/pip-req-build-69ukzo_1/build/lib.linux-x86_64-3.8 -DPYTHON_EXECUTABLE:FILEPATH=/root/.cache/pypoetry/virtuale
nvs/kheironml-VsnhxLU2-py3.8/bin/python
```

And I can import tensorflow via that direct path and the virtual env.

**Comment by joeyearsley** [comment]
If I clone and build from source it works correctly, I'll open a ticket in poetry as well in case it is an issue with their installer

**Comment by joeyearsley** [comment]
Having spoken to the poetry team they believe the issue lies in Horovod not being compliant with PEP-517/518, is this correct?

If so, are there any plans to resolve this?

**Comment by maxhgerlach** [comment]
> Having spoken to the poetry team they believe the issue lies in Horovod not being compliant with PEP-517/518, is this correct?

Would that be related to the observations in issue and and comments https://github.com/horovod/horovod/issues/3483? I think it would be great to clear that up and assistance would be appreciated!

**Comment by joeyearsley** [comment]
The best I can say is it might be, however on my system I've got TensorFlow already installed and poetry seems to be resolving to install it before horovod. 
So I believe it's due to [PEP-517 ](https://peps.python.org/pep-0517/) and building from source in isolation needing the requirements to be pre-set in the setup-requires or pyproject, as you suggested. 

I wonder if there needs to be another PEP to make a standard where isolation can also mean exposing the extras required rather than just those in the setup.py/pyproject.

**Comment by geroldcsendes** [comment]
I am facing the same issue. Raised a ticket at [poetry](https://github.com/python-poetry/poetry/issues/6899) and they said the horovod's build is not compliant with PEP-517 as mentioned above by @joeyearsley

**Comment by itsdani** [comment]
The install with the latest poetry now fails with
```
[...]
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for horovod
Failed to build horovod
ERROR: Could not build wheels for horovod, which is required to install pyproject.toml-based projects
  ```

It also fails with the same error using `pip install --use-pep517 horovod` (which is what poetry uses in the background)

**Comment by itsdani** [comment]
This current issue is introduced in `0.26.0`, as `poetry add horovod==0.25.0` works fine.

**Comment by itsdani** [comment]
I'm wondering if this should be a new issue. The original error doesn't happen anymore with poetry `1.2.2` and this new issue doesn't happen with the `Horovod version: 0.24.2` in the issue description

**Environment:**
1. Framework: -
2. Framework version: -
3. Horovod version: 0.26.0, 0.26.1
4. MPI version: -
5. CUDA version: -
6. NCCL version: -
7. Python version: 3.10.7
8. Spark / PySpark version: -
9. Ray version: -
10. OS and version: Ubuntu 20.04 and Endeavour OS
11. GCC version: 12.2.0
12. CMake version: 3.24.2

**Comment by EnricoMi** [comment]
Error `No module named 'packaging'` with Horovod 0.26.0 is a different issue: #3744
That has been fixed with release 0.26.1: https://github.com/horovod/horovod/releases/tag/v0.26.1

**Comment by itsdani** [comment]
This still happens with poetry for `0.26.1`, I have explicitly tried `poetry add horovod==0.26.1`

**Comment by EnricoMi** [comment]
@itsdani you are saying the issue described in this issue's description is fixed with petry `1.2.2`?

**Comment by itsdani** [comment]
Yes, the `No module named 'tensorflow'` doesn't happen with `poetry 1.2.2`

**Comment by maxhgerlach** [comment]
If the `packaging` import is a problem now, I suspect that the install process just doesn't get far enough to surface the `No module named 'tensorflow'` error.

As a user of Horovod, I'd suggest to separately build a Horovod wheel adapted for your environment (with all flags configured appropriately and all external dependencies installed with the right versions; `HOROVOD_LOCAL_VERSION` set to some internal value) and then use that in your Python dependency management systems.

**Comment by itsdani** [comment]
The `No module named 'tensorflow'` problem doesn't happen on `poetry 1.2.2` for `horovod 0.25.0`, the install succeeds without any errors.

I have commented on the other closed issue (https://github.com/horovod/horovod/issues/3744) regarding `No module named 'packaging'`, because my issue is the same and the current fix doesn't work with `pip install --use-pep517`

**Comment by maxhgerlach** [comment]
Would you know how to configure the dependence on `packaging` in setup.py in a way that it works with `pip install --use-pep517`?

**Comment by itsdani** [comment]
> Would you know how to configure the dependence on `packaging` in setup.py in a way that it works with `pip install --use-pep517`?

Sadly I have no idea how any of this works :(

**Comment by itsdani** [comment]
I have found a solution. Adding a `pyproject.toml` with build-system dependencies to horovod, containing this fixes the issue, since PEP-517 and 518 specifies the use of pyproject.toml for things like this.

I'm not entirely sure which issue I should reference in the PR (#3758) at this point.

**Comment by itsdani** [comment]
I'm not sure, but using package [extras](https://peps.python.org/pep-0508/#extras) might also be a viable thing for declaring build dependencies, and there might be no need for a custom build backend. This might, however, require changes to the current build process, e.g. setting the env-vars for the build based on selected extras (like `HOROVOD_WITH_TENSORFLOW=1`), or changing the build to select dependencies another way instead of these env-vars.

This is just an idea though, I'm not really working on this
